---
- name: Up site
  hosts: all
  become: yes
  tasks:
          - name: Copy script up site
            copy:
                    src: up-site.sh
                    dest: /bin
                    mode: a+x

          - name: Run script up site
            command: '/bin/bash up-site.sh'
